
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

services:
    - docker

before_install:
    sudo apt-get update &&
    sudo apt-get dist-upgrade &&
    sudo apt-get install curl wget gnupg2 make

install:
    make build

script:
    make build
