FROM alpine:3.7
#TODO: make the hosts and ports changable by passing arguments instead of modifying the torrc
#ARG TOR_CONTROL_HOST=127.0.0.1
#ARG TOR_CONTROL_PORT=9151
#ARG TOR_SOCKS_HOST=127.0.0.1
#ARG TOR_SOCKS_PORT=9150
RUN apk update && apk add tor
COPY torrc /etc/tor/torrc
RUN mkdir -p /var/lib/tor
RUN chown -R tor /var/lib/tor
RUN chmod -R 2700 /var/lib/tor
RUN chmod -R o+rw /var/lib/tor
USER tor
CMD tor -f /etc/tor/torrc
